export const GETBOOK_REQUEST = "GETBOOK_REQUEST"
export const GETBOOK_SUCCESS = "GETBOOK_SUCCESS"
export const GETBOOK_FAIL = "GETBOOK_FAIL"

export const CREATE_BOOK_REQUEST = "CREATE_BOOK_REQUEST";
export const CREATE_BOOK_SUCCESS = "CREATE_BOOK_SUCCESS";
export const CREATE_BOOK_FAIL = "CREATE_BOOK_FAIL";
export const CREATE_BOOK_RESET = "CREATE_BOOK_RESET"

export const GETSINGLE_BOOK_REQUEST = "GETSINGLE_BOOK_REQUEST"
export const GETSINGLE_BOOK_SUCCESS = "GETSINGLE_BOOK_SUCCESS"
export const GETSINGLE_BOOK_FAIL = "GETSINGLE_BOOK_FAIL"

export const UPDATE_BOOK_REQUEST = "UPDATE_BOOK_REQUEST"
export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS"
export const UPDATE_BOOK_FAIL = "UPDATE_BOOK_FAIL"
export const UPDATE_BOOK_RESET = "UPDATE_BOOK_RESET"

export const DELETE_BOOK_REQUEST = "DELETE_BOOK_REQUEST"
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS"
export const DELETE_BOOK_FAIL = "DELETE_BOOK_FAIL"
export const DELETE_BOOK_RESET = "DELETE_BOOOK_RESET"

export const CLEAR_ERROR = "CLEAR_ERROR"
